id: 9e60de78f0ad41c187e017cb040a2571
initial_creation_type: ocr
source_metadata:
  volumes:
    2407560c55364f908add431e2c86ba8c:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: བྱང་ཆུབ་སེམས་དཔའི་ནོར་བུའི་ཕྲེང་བ།
      total_pages: 1902
      volume_number: 64
